import type { Metadata } from 'next'
export const metadata: Metadata = { title: 'Privacy Policy – ScoreNexa', description: 'How ScoreNexa collects, uses and protects your personal data.' }
export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold text-slate-900 mb-2" style={{fontFamily:'Oswald,sans-serif'}}>PRIVACY POLICY</h1>
      <p className="text-slate-400 text-sm mb-8">Last updated: {new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</p>
      <div className="space-y-6 text-slate-700 leading-relaxed text-sm">
        <p>ScoreNexa ("we", "us", "our") is committed to protecting your privacy. This policy explains how we collect, use and safeguard your personal data when you use scorenexa.com.</p>
        <h2 className="text-lg font-bold text-slate-900 mt-6" style={{fontFamily:'Oswald,sans-serif'}}>1. INFORMATION WE COLLECT</h2>
        <p>We collect information you provide when registering (name, email, password), information generated by your use of our services (pages viewed, articles read, search terms), and technical information including IP address, browser type, and device identifiers. We may also use Google Analytics and Google AdSense, which set cookies for advertising and analytics purposes.</p>
        <h2 className="text-lg font-bold text-slate-900 mt-6" style={{fontFamily:'Oswald,sans-serif'}}>2. HOW WE USE YOUR DATA</h2>
        <p>We use collected information to provide and improve our services, personalise your experience, send newsletters (with your consent), display relevant advertising via Google AdSense, and comply with legal obligations.</p>
        <h2 className="text-lg font-bold text-slate-900 mt-6" style={{fontFamily:'Oswald,sans-serif'}}>3. GOOGLE ADSENSE & COOKIES</h2>
        <p>ScoreNexa uses Google AdSense to display advertisements. Google and its partners may use cookies to serve ads based on your prior visits to our site or other sites. You may opt out of personalised advertising by visiting Google's Ads Settings. We use cookies to improve your experience and analyse site traffic.</p>
        <h2 className="text-lg font-bold text-slate-900 mt-6" style={{fontFamily:'Oswald,sans-serif'}}>4. YOUR RIGHTS</h2>
        <p>You have the right to access, correct or delete your personal data at any time. To exercise these rights, contact us at privacy@scorenexa.com. You may also unsubscribe from marketing emails at any time via the link in any email we send.</p>
        <h2 className="text-lg font-bold text-slate-900 mt-6" style={{fontFamily:'Oswald,sans-serif'}}>5. CONTACT</h2>
        <p>For privacy enquiries, contact: <a href="mailto:privacy@scorenexa.com" className="text-blue-600">privacy@scorenexa.com</a></p>
      </div>
    </div>
  )
}
